name: perf_load_test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run performance test
      - name: Run performance tests
        run: npm run perf
  load-test:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Setup Node.js 18
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'
    
        - name: Install Artillery and polyfill
          run: |
            npm install -g artillery
            npm install web-streams-polyfill
        
        - name: Run load test
          run: npm run load